project_id = "xqmnycilpyluuthanhdt"

[functions.generate-study-content]
verify_jwt = true

[functions.generate-mock-paper]
verify_jwt = true

[functions.evaluate-answer-sheet]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false